# Common data for pipeline
# Use quoted keys to avoid interpreting of keys

# Location of data, either relative to the "workflow.nf" script, as an
# absolute path, or prefixed with ${projectDir}
[data]

# Paths
species = "wheat"
meta = "${projectDir}/meta.tsv"
path = "${projectDir}/../data"
out = "${projectDir}/../data"
bin = "${projectDir}/bin"
reports = "${projectDir}/../reports"
logs = "${projectDir}/logs"

# Reads
reads = "reads"
reads_unzipped = "reads-extracted"
reads_trimmed = "reads-trimmed"
reads_length = 150 # Length of reads

glob = "*_r{1,2}*.fastq.gz"
glob_unzipped = "*_r{1,2}*.fastq"
glob_trimmed = "trim_*_r{1,2}*.fastq"

# Alignments
bam = "bam"
bam_star_sorted = "Aligned.sortedByCoord.out.bam"

# Genomes
# Expects files with the base name "genome" (i.e. genome.fasta, genome.gtf)
genomes = "genomes" # Path in data folder
genes = "genes"
fungi = "ptr"
plant = "wheat"

# Proteins
proteins = "proteins"

# Adapters
adapters = "adapters.fasta"

time = "time"
fastp = "fastp"
fastqc = "fastqc"
star = "star"
tablemaker = "tablemaker"
trinity = "trinity"


[wheat]
max_intron_length = 30000


[ptr]
max_intron_length = 6000


# Metadata information, enable "use_meta" in "settings.toml" to enable
[meta]

# List of factors in selecting files
factors = ["cultivar", "control", "time"]

# Factor used to group individual samples
group = "cultivar"


[qc]

# Quality cutoff (PHRED score)
quality = 20

# Number of bases to trim from the front
# Default: 4
trimf = 10

# Number of bases to trim from the tail
# Default: 0
trimt = 5

# Autodetection of adapter sequences
# Default: false
autodetect = true

# Compression of reads, only effective if compression is enabled in
# settings.toml
# Default: true
compress = true

# Compression level
# Default: 5
compress_level = 5
