# Configuration of Nextflow processes
[process]
module = [
    "singularity/3.11.4-nompi",
    "openjdk/17.0.5_8",
    "parallel/20220522",
    "trinity/2.13.2--hea94271_3",
]
# beforeScript = "source ${projectDir}/templates/mamba.sh"
executor = "slurm"
queue = "work"
queueSize = 4
# clusterOptions = "--qos high"

# Other pipeline configurations
[time]
bin = "/usr/bin/time"
flags = "-v"

[parallel]
bin = "parallel"
flags = ""

[xargs]
bin = "xargs"
flags = ""


# Container engine parameters
[container]

# Container engine binary
# Default: ./
bin = "singularity"

# Container engine options
# Default:
opts = ""

# Container runtime command
# Default: exec
exec = "exec"

# Options to append to the runtime command
# Default:
exec_opts = ""

# Enable the usage of a single container for the pipeline, see entry below to
# set path to the container.
# Default: true
monolithic = true

# Path to a container containing all binaries and tools used for the pipeline,
# only functional if monolithic is set to true, otherwise containers are loaded
# per-module.
# Default: NA
path = "${projectDir}/../containers/biology.sif"


# Module settings
[tools]
bc = "bc"
wc = "wc"


[extract]
# Resources
cores = 8
memory = 8
buffer = 8 # Set to a value greater than 1 to enable process buffering

# Container options, corrects mismatched reads on alignment
container = false
direct = false

# Command
bin = "pigz"
flags = ""


[fastp]
cores = 4
memory = -1
buffer = 8
time = 1

container = true
direct = false
path = "${projectDir}/../containers/biology.sif"

bin = "fastp"
flags = ""


[gffread]
cores = 8
memory = 10
buffer = 1
time = 1

container = true
direct = false
path = "${projectDir}/../containers/biology.sif"

bin = "gffread"
flags = ""


[star]
cores_align = 64
cores_index = 8
memory_align = 100
memory_index = 100
buffer = 8
buffer_align = 8
buffer_index = 1
time_align = 24
time_index = 6

queue_align = "work"
queue_index = "work"

container = true
direct = false
path = "${projectDir}/../containers/biology.sif"

bin = "STAR"
flags = ""


[tablemaker]
# Resources
cores = 4
memory = 10
time = 1
queue = "work"

# Container options
container = false
path = "${projectDir}/../containers/biology.sif"

# Command
bin = "tablemaker"
flags = ""


[trinity]
# Resources
cores_s1 = 32
memory_s1 = 230
time_s1 = 24
queue_s1 = "highmem"

# Container options
container = false
direct = false
path = "${projectDir}/../containers/biology.sif"

# Command
bin = "Trinity"
flags = ""


[interpro]
# Resources
cores = 16
memory = 60
time = 24
queue = "work"

# Container options
container = false
path = "${projectDir}/../containers/biology.sif"

# Command
bin = "interproscan.sh"
flags = ""


[fastqc]
# Resources
cores = 1
memory = -1

# Container options
container = false
direct = false
path = "${projectDir}/../containers/biology.sif"

# Command
bin = "fastqc"
flags = ""


[multiqc]
# Resources
cores = 1
memory = 1

# Container options
container = true
direct = false
path = "${projectDir}/../containers/biology.sif"

# Command
bin = "multiqc"
flags = ""


[samtools]
# Resources
cores = 16
memory = 20
time = 6
buffer = 2

# Container options
container = false
direct = false
path = "${projectDir}/../containers/biology.sif"

# Command
bin = "samtools"
bin_merge = "merge"
flags = ""


[seqkit]
# Resources
cores = 8
memory = 1
time = 1
buffer = 1

# Container options
container = true
direct = false
path = "${projectDir}/../containers/biology.sif"

# Command
bin = "seqkit"
flags = ""
